## Sampling rate
#fs: 8000
#fs: 16000
#fs: 22050
fs: 24000
#fs: 44100
#fs: 48000

## Frame-shift mel-cep/mel-spec extraction
#shiftms: 5
shiftms: 10

## Window length mel-spectrogram extraction
winms: 27.5

## DC-component removal
highpass_cutoff: 65

## Mel-cepstrum
mcep_dim: 49

## Mel-spectrogram
mel_dim: 80

## Pre-emphasis noise-shaping coefficient
alpha: 0.85

## GRU hidden units encoder, decoder spec, decoder excit, post-net
hidden_units_enc: 512
hidden_units_dec: 640
hidden_units_lf0: 128
hidden_units_post: 160

## GRU hidden units wavernn
#[for high-quality, 0.36 RT with 10-bit mu-law 10 ms shift]
#hidden_units_wave: 800
#[for natural-quality, 0.45 RT with 10-bit mu-law 10 ms shift]
hidden_units_wave: 896

hidden_units_wave_2: 32

#[for others]
#mid_dim: 32
#[for 10-bit mu-law]
mid_dim: 16

## GRU hidden layers encoder, decoder spec, decoder excit, post-net
hidden_layers_enc: 1
hidden_layers_dec: 1
hidden_layers_lf0: 1
hidden_layers_post: 1

## GRU hidden layers wavernn
hidden_layers_wave: 1

## kernel-size input conv encoder
kernel_size_enc: 5
dilation_size_enc: 1

## kernel-size input conv decoder spec
kernel_size_dec: 5
dilation_size_dec: 1

## kernel-size input conv encoder excit
kernel_size_lf0: 7
dilation_size_lf0: 1

## kernel-size input conv post-net
kernel_size_lf0: 7
dilation_size_lf0: 1

## kernel-size input conv wavernn
kernel_size_wave: 7
dilation_size_wave: 1

## shallow WaveNet hyperparams.
kernel_size: 7
hid_chn: 256
skip_chn: 256
dilation_depth: 3
dilation_repeat: 2

## for using skewed input convolution (> 0), or balanced (0) [only for encoder]
right_size_enc: 1
#right_size_enc: 2
right_size_dec: 0
right_size_lf0: 0
right_size_post: 0
## lookup frame limited to only 1/2 frame [for allowing low-latency/real-time processing]
right_size_wave: 1
#right_size_wave: 2

## number of cycles :  n_half_cyc // 2
n_half_cyc: 2
#n_half_cyc: 4
## if cyclevae, use n_half_cyc:2, i.e., 1 cycle
## if cyclevqvae, use n_half_cyc:4, i.e., 2 cycles

## spect. latent dim.
lat_dim: 96

## excit. latent dim.
lat_dim_e: 32

## codebook size for cyclevqvae
ctr_size: 128

## use causal input convolution
## if using skewed input convolution for encoder (right_size > 0), set causal_conv dec/lf0 to true
## always use non-causal input conv. for encoder/wave
causal_conv_enc: false
causal_conv_dec: true
causal_conv_lf0: true
causal_conv_post: true
causal_conv_wave: false
## if right_size > 0 (skewed conv encoder, i.e., future frame is limited), set causal_conv dec/lf0 to true [low-latency/real-time proc.]

## use dim-reduction for cont. spk. embed from 1-hot code (only for cyclevae spec-excit)
#spkidtr_dim: 0
spkidtr_dim: 2
## to freely interpolate between 2-dim cont. spk-space

## learning rate
lr: 1e-4

## dropout rate
do_prob: 0.5

## maximum step count
step_count: 1065000
step_count_wave: 3670000

## Batch sequence length setting for spectral/excitation modeling
## 30 frames
batch_size: 30

## Batch sequence length setting for waveform modeling
## 4 frames for wavernn with 10 ms
batch_size_wave: 4
## 8 frames for wavernn with 5 ms
#batch_size_wave: 8

# number of workers (threads) for batch data handling
n_workers: 2

mdl_name: cycmelspxlf0capspkvae-laplace_sparse

mdl_name_post: cycmelspxlf0capspkvae-laplace_post-smpl

##[8 kHz, 16 kHz, 22.05 kHz, 24 kHz]
#mdl_name_wave: wavernn_dualgru_compact_lpc_mband_9bit
##[8 kHz, 16 kHz, 22.05 kHz, 24 kHz, 44.1 kHz, 48 kHz]
mdl_name_wave: wavernn_dualgru_compact_lpc_mband_10bit_cf
##[8 kHz, 16 kHz, 22.05 kHz, 24 kHz]
#mdl_name_wave: wavernn_dualgru_compact_lpc_mband_16bit

## sparsification scheduling settings for cyclevae
t_start_cycvae: 5000
t_end_cycvae: 245000
interval_cycvae: 10
densities_cycvae: 0.36-0.36-0.48
n_stage_cycvae: 4

## sparsification scheduling settings for wavernn
t_start: 20000
t_end: 1270000
interval: 20
densities: 0.09-0.09-0.12
n_stage: 4

## number of data-driven linear predictive coefficients (LPC) in wavernn
#lpc: 0
#lpc: 4
lpc: 6

#use_mcep: true
## mel-spectrogram-based modeling (wavernn)
use_mcep: false

## only if using mel-spectrogram, if set true, melsp+f0
with_excit: false
#with_excit: true
